title: Michael Humiston
description:  Michael Humiston's home on the web. Software engineer. I build things. Usually they work.
content: Software engineer. I build things. Usually they work.

social:
  - platform: GitHub
    url: https://github.com/mhum
    icon: github.svg
  - platform: LinkedIn
    url: https://www.linkedin.com/in/michaelhumiston
    icon: linkedin.svg

url: https://michaelhumiston.com/
baseurl: ""
markdown: kramdown
sharing_image: share.jpg
google_analytics: "G-1VXRBR26Z9"

half_side: right
full_text_position: center
